<#
.LICENSE
    SPDX-License-Identifier: GPL-2.0-or-later

.SYNOPSIS
    Configure and build one CMake preset of a GMS2 C++ extension, locate the
    resulting shared library, optionally collect artifacts to a folder, and
    optionally package the Android .so files into lib.jar. With -GmsProject,
    the built artifacts and the extension_manifest.json function list are
    synced into the GameMaker project automatically.

.DESCRIPTION
    Works with the project layout generated by scaffold_extension.py.

    - Local presets (Windows x64, Android ABIs) run directly.
    - Linux/macOS/iOS presets are remote builds and must be built through
      Visual Studio's remote connection; this script cannot reach them.
    - Ninja + cl.exe (Windows preset) requires the MSVC environment: run from
      a VS Developer PowerShell or "x64 Native Tools Command Prompt", or build
      from Visual Studio instead.

.EXAMPLE
    powershell -File build_extension.ps1 -ProjectDir F:\dev\ext_audio -Preset x64-release
    powershell -File build_extension.ps1 -ProjectDir F:\dev\ext_audio -Preset arm64-v8a -PackAndroid
    powershell -File build_extension.ps1 -ProjectDir F:\dev\ext_audio -Preset x64-release -CollectTo F:\gms\extensions\ext_audio
    powershell -File build_extension.ps1 -ProjectDir F:\dev\ext_audio -Preset x64-release `
        -GmsProject F:\gms\MyGame -GmsManifest F:\dev\ext_audio\extension_manifest.json
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectDir,

    [Parameter(Mandatory = $true)]
    [string]$Preset,

    [switch]$PackAndroid,

    [string]$CollectTo,

    [string]$GmsProject,

    [string]$GmsManifest,

    [string]$SyncScript
)

$ErrorActionPreference = 'Stop'

function Resolve-Dir([string]$Path) {
    if (-not [System.IO.Path]::IsPathRooted($Path)) {
        $Path = Join-Path (Get-Location) $Path
    }
    return [System.IO.Path]::GetFullPath($Path)
}

$projectRoot = Resolve-Dir $ProjectDir
$presetsFile = Join-Path $projectRoot 'CMakePresets.json'
if (-not (Test-Path -LiteralPath $presetsFile)) {
    throw "CMakePresets.json not found in '$projectRoot'. Is this a CMake extension project?"
}

$cmake = Get-Command cmake -ErrorAction SilentlyContinue
if (-not $cmake) {
    throw "cmake was not found on PATH. Install CMake (or build from Visual Studio)."
}

$presets = Get-Content -Raw -LiteralPath $presetsFile | ConvertFrom-Json
$allPresets = @($presets.configurePresets)
$cfg = @($allPresets | Where-Object { $_.name -eq $Preset })[0]
if (-not $cfg) {
    $available = @($allPresets | ForEach-Object { $_.name }) -join ', '
    throw "Preset '$Preset' not found in configurePresets. Available: $available"
}

# Resolve inherited properties (e.g. Android ABI presets inherit android-common).
$cur = $cfg
$chain = @()
$seen = @{}
while ($cur) {
    if ($seen.ContainsKey($cur.name)) { break }
    $seen[$cur.name] = $true
    $chain = @($cur) + $chain
    if ($cur.inherits) {
        $cur = @($allPresets | Where-Object { $_.name -eq $cur.inherits })[0]
    } else {
        $cur = $null
    }
}
$generator = [string]($chain | ForEach-Object { $_.generator } | Where-Object { $_ } | Select-Object -Last 1)
$binaryDir = [string]($chain | ForEach-Object { $_.binaryDir } | Where-Object { $_ } | Select-Object -Last 1)
if (-not $binaryDir) { $binaryDir = '${sourceDir}/out/build/${presetName}' }
$binaryDir = $binaryDir.Replace('${sourceDir}', $projectRoot).Replace('${presetName}', $Preset)
$binaryDir = $binaryDir.Replace('/', [System.IO.Path]::DirectorySeparatorChar)

if ($generator -like 'Ninja*' -and $cfg.cacheVariables.CMAKE_CXX_COMPILER -eq 'cl.exe') {
    Write-Warning "The Windows preset uses Ninja + cl.exe, which requires the MSVC environment. Run this script from a VS Developer PowerShell or 'x64 Native Tools Command Prompt', or build from Visual Studio."
}

Write-Host "==> Configuring preset '$Preset' in $projectRoot"
Push-Location $projectRoot
try {
    & $cmake.Source '--preset' $Preset
    if ($LASTEXITCODE -ne 0) { throw "cmake configure failed for preset '$Preset' (exit code $LASTEXITCODE)." }

    Write-Host "==> Building preset '$Preset'"
    $buildArgs = @('--build', $binaryDir)
    if ($generator -like 'Visual Studio*') { $buildArgs += @('--config', 'Release') }
    & $cmake.Source @buildArgs
    if ($LASTEXITCODE -ne 0) { throw "cmake build failed for preset '$Preset' (exit code $LASTEXITCODE)." }
}
finally {
    Pop-Location
}

Write-Host "==> Locating shared library artifacts under $binaryDir"
$artifacts = @()
if (Test-Path -LiteralPath $binaryDir) {
    $artifacts = @(Get-ChildItem -Path $binaryDir -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Extension -in '.dll', '.so', '.dylib' })
}
if ($artifacts.Count -eq 0) {
    Write-Warning "No .dll/.so/.dylib artifacts found under '$binaryDir'."
} else {
    foreach ($a in $artifacts) { Write-Host "ARTIFACT: $($a.FullName)" }
}

if ($CollectTo) {
    $dest = Resolve-Dir $CollectTo
    New-Item -ItemType Directory -Force -Path $dest | Out-Null
    foreach ($a in $artifacts) {
        Copy-Item -LiteralPath $a.FullName -Destination $dest -Force
        Write-Host "COPIED: $($a.FullName) -> $dest"
    }
}

if ($GmsProject) {
    Write-Host "==> Syncing extension into GMS project: $GmsProject"
    $sync = $SyncScript
    if (-not $sync) { $sync = Join-Path $PSScriptRoot 'sync_gms_extension.py' }
    if (-not (Test-Path -LiteralPath $sync)) {
        throw "sync_gms_extension.py not found at '$sync'. Pass -SyncScript <path> or run it directly."
    }
    $py = Get-Command python -ErrorAction SilentlyContinue
    if (-not $py) { throw "python not found on PATH; cannot sync the GMS project." }
    $syncArgs = @('--project', $GmsProject)
    if ($GmsManifest) { $syncArgs += @('--manifest', $GmsManifest) }
    if ($artifacts.Count -eq 0) {
        Write-Warning "No .dll/.so/.dylib artifacts found; only the function list will be updated."
    }
    foreach ($a in $artifacts) { $syncArgs += @('--artifact', $a.FullName) }
    & python $sync @syncArgs
    if ($LASTEXITCODE -ne 0) { throw "GMS sync failed (exit code $LASTEXITCODE)." }
}

if ($PackAndroid) {
    Write-Host "==> Packaging Android lib.jar"
    $abis = @('x86_64', 'arm64-v8a', 'armeabi-v7a')
    $libRoot = Join-Path ([System.IO.Path]::GetTempPath()) ('gms_jar_' + [guid]::NewGuid().ToString('N'))
    $libDir = Join-Path $libRoot 'lib'
    New-Item -ItemType Directory -Force -Path $libDir | Out-Null

    $foundAny = $false
    foreach ($abi in $abis) {
        $abiOut = Join-Path $projectRoot ("out\build\android\" + $abi)
        $abiDir = Join-Path $libDir $abi
        New-Item -ItemType Directory -Force -Path $abiDir | Out-Null
        $soFiles = @()
        if (Test-Path -LiteralPath $abiOut) {
            $soFiles = @(Get-ChildItem -Path $abiOut -Recurse -File -Filter '*.so' -ErrorAction SilentlyContinue)
        }
        if ($soFiles.Count -gt 0) {
            Copy-Item -LiteralPath $soFiles[0].FullName -Destination $abiDir -Force
            Write-Host "JAR ABI: $abi <- $($soFiles[0].FullName)"
            $foundAny = $true
        } else {
            Write-Warning "No .so found for ABI '$abi' (expected under out\build\android\$abi). lib.jar will miss this ABI."
        }
    }

    if ($foundAny) {
        $jarPath = Join-Path $projectRoot 'lib.jar'
        $zipPath = Join-Path $projectRoot 'lib.zip'
        if (Test-Path -LiteralPath $jarPath) { Remove-Item -LiteralPath $jarPath -Force }
        Compress-Archive -Path $libDir -DestinationPath $zipPath -Force
        Move-Item -LiteralPath $zipPath -Destination $jarPath -Force
        Write-Host "ANDROID JAR: $jarPath"
    } else {
        Write-Warning "No Android .so artifacts found; skipping lib.jar."
    }

    Remove-Item -LiteralPath $libRoot -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host "Done."
